/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eve.database;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author spencer
 */
public class MapGenerator extends javax.swing.JPanel {
    String RegionsArray[];
    private boolean Nullsec= true;
    private boolean Lowsec= true;
    private boolean Highsec= true;
    private boolean useID=true;
    private int transFilter=0;
    private int FilterQuantity;
    private String item;
    private String itemContains;
    private String selectedRegion=null;
    private String selectedFilter="Connections";

    /**
     * Creates new form MapGenerator
     */
    public MapGenerator() throws SQLException {
        Database_IO base = new Database_IO();
        RegionsArray= base.getRegionNames();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDNameToggle = new javax.swing.ButtonGroup();
        filterToggle = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filterSystems = new javax.swing.JRadioButton();
        filterQuantity = new javax.swing.JComboBox<>();
        filterType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        transOf = new javax.swing.JRadioButton();
        itemBox = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        idtoggle = new javax.swing.JRadioButton();
        nametoggle = new javax.swing.JRadioButton();
        NoneTrans = new javax.swing.JRadioButton();
        NullSec = new javax.swing.JCheckBox();
        LowSec = new javax.swing.JCheckBox();
        HighSec = new javax.swing.JCheckBox();
        Region = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Execute = new javax.swing.JButton();

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        filterToggle.add(filterSystems);
        filterSystems.setText("Show systems with");
        filterSystems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSystemsActionPerformed(evt);
            }
        });

        filterQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        filterQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterQuantityActionPerformed(evt);
            }
        });

        filterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stations", "Sell Orders", "Buy Orders", " ", " " }));
        filterType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("present.");

        filterToggle.add(transOf);
        transOf.setText("Transactions of Item");
        transOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transOfActionPerformed(evt);
            }
        });

        itemBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBoxActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IDNameToggle.add(idtoggle);
        idtoggle.setSelected(true);
        idtoggle.setText("ID");
        idtoggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtoggleActionPerformed(evt);
            }
        });

        IDNameToggle.add(nametoggle);
        nametoggle.setText("Name");
        nametoggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametoggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametoggle)
                    .addComponent(idtoggle)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idtoggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametoggle))
        );

        filterToggle.add(NoneTrans);
        NoneTrans.setSelected(true);
        NoneTrans.setText("None");
        NoneTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(transOf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NoneTrans))
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filterSystems)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(NoneTrans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transOf, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterSystems)
                    .addComponent(filterQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        NullSec.setSelected(true);
        NullSec.setText("Null Sec < .1");
        NullSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NullSecActionPerformed(evt);
            }
        });

        LowSec.setSelected(true);
        LowSec.setText("Low Sec .1 < < .5");
        LowSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowSecActionPerformed(evt);
            }
        });

        HighSec.setSelected(true);
        HighSec.setText("High Sec .5 <");
        HighSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighSecActionPerformed(evt);
            }
        });

        Region.setModel(new javax.swing.DefaultComboBoxModel<>(RegionsArray));
        Region.setSelectedIndex(0);
        Region.setSelectedItem(0);
        Region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegionActionPerformed(evt);
            }
        });

        jLabel2.setText("Show Region:");

        Execute.setText("Execute");
        Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Execute)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LowSec)
                            .addComponent(HighSec)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NullSec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(NullSec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LowSec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HighSec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Execute)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterSystemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterSystemsActionPerformed
        transFilter=3;
    }//GEN-LAST:event_filterSystemsActionPerformed

    private void ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteActionPerformed
        try {
            System.out.println("N"+Nullsec+"L"+Lowsec+"H"+Highsec);
            item=itemBox.getText();
            Map Amap= new Map(selectedRegion,Highsec,Lowsec,Nullsec,transFilter,useID,FilterQuantity,item,selectedFilter);
        } catch (SQLException ex) {
            Logger.getLogger(MapGenerator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExecuteActionPerformed

    private void filterQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterQuantityActionPerformed
        FilterQuantity=Integer.parseInt((String)filterQuantity.getSelectedItem());
    }//GEN-LAST:event_filterQuantityActionPerformed

    private void RegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegionActionPerformed
        
        selectedRegion = (String)Region.getSelectedItem();
        
    }//GEN-LAST:event_RegionActionPerformed

    private void HighSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighSecActionPerformed
        Highsec=!Highsec;
    }//GEN-LAST:event_HighSecActionPerformed

    private void NoneTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneTransActionPerformed
         transFilter=0;
    }//GEN-LAST:event_NoneTransActionPerformed

    private void LowSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowSecActionPerformed

        Lowsec=!Lowsec;
    }//GEN-LAST:event_LowSecActionPerformed

    private void NullSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NullSecActionPerformed

        Nullsec=!Nullsec;
    }//GEN-LAST:event_NullSecActionPerformed

    private void transOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transOfActionPerformed
        transFilter=1;
    }//GEN-LAST:event_transOfActionPerformed

    private void idtoggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtoggleActionPerformed
        useID=!useID;
        System.out.println(useID);
    }//GEN-LAST:event_idtoggleActionPerformed

    private void nametoggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametoggleActionPerformed
        useID=!useID;
                System.out.println(useID);

    }//GEN-LAST:event_nametoggleActionPerformed

    private void itemBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBoxActionPerformed

    private void filterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTypeActionPerformed
                selectedFilter = (String)filterType.getSelectedItem();
                System.out.println(selectedFilter);

    }//GEN-LAST:event_filterTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Execute;
    private javax.swing.JCheckBox HighSec;
    private javax.swing.ButtonGroup IDNameToggle;
    private javax.swing.JCheckBox LowSec;
    private javax.swing.JRadioButton NoneTrans;
    private javax.swing.JCheckBox NullSec;
    private javax.swing.JComboBox<String> Region;
    private javax.swing.JComboBox<String> filterQuantity;
    private javax.swing.JRadioButton filterSystems;
    private javax.swing.ButtonGroup filterToggle;
    private javax.swing.JComboBox<String> filterType;
    private javax.swing.JRadioButton idtoggle;
    private javax.swing.JTextField itemBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton nametoggle;
    private javax.swing.JRadioButton transOf;
    // End of variables declaration//GEN-END:variables
}
